export enum ActionType {
  CHATS_LOADED = "chats_loaded",
  CHOOSE_CHAT = "choose_chat",
  DEAUTH = "deauth",
  AUTH = "auth",
  TOREGISTER = "to_register",
  TOLOGIN = "to_login",
  INITIALISE_SOCKET = "initialise_socket",
  REFRESH_AVATAR = "refresh_avatar",
  SET_ANOTHER_USER_PROFILE = "set_another_user_profile",
  SHOW_PROFILE = "show_profile",
  SHOW_IMAGE = "show_image",
  START_NEW_CHAT = "start_new_chat",
  NEW_CHAT = "new_chat",
  NEW_CHAT_SEARCH_QUERY = "new_chat_search_query",
  TOGGLE_NOTIFICATIONS = "toggle_notifications",
}
